### ISSUE TITLE
Jstr.concat produce wrong result

### ISSUE THREAD

**Issue by Chimrod** [dbuenzli/brr#14]
I have something strange with Jstr.concat:

this code:

```ocaml
    let message = Jstr.(concat [ v "A"; v "B"; v "C"]) in
    Console.(log [message]);
```

produce this output in the console :  `AB,C`. The expected result is `ABC` (without coma).

I have taken a look in the code, and except the call to external `caml_list_of_js_array` I do not see anything wrong. The coma in the second place seems indicate a wrong parameter in the call, but I cannot see where this definition comes from.

**Comment by dbuenzli** [comment]
Confirmed. It seems there's an issue with that optional argument.

```ocaml
#  let message = Jstr.(concat [ v "A"; v "B"; v "C"]);;
val message : Jstr.t = Jstr.v "AB,C"
# let message = Jstr.(concat ~sep:(v "") [ v "A"; v "B"; v "C"]);;
val message : Jstr.t = Jstr.v "ABC"
```

**Comment by dbuenzli** [comment]
Ah different code paths…

But that's [obviously wrong](https://github.com/dbuenzli/brr/blob/2065b9d8c861eb151b1ff398c76dd0f946d5ee75/src/jstr.ml#L65). It's doing `v0.concat([v1, v2, v2, …])` instead of `v0.concat(v1, v2, v2, ...)`.

**Comment by dbuenzli** [comment]
Sorry for the bug and thanks for the report. I have no idea how my brain managed to come up with such a convoluted implementation.

**Comment by Chimrod** [comment]
Thanks for the correction !

Well, maybe I have the same brain as you as I understand what you did:

- use the separator is given, use it :) 
- when no separator is given, avoid unneeded call to join, and directly call the concat function. 

What was wrong is that `caml_list_of_js_array` return an array, So, the line `jv_call s "concat" [| jv_of_jstr_list ss |]` should have been writen `jv_call s "concat" (jv_of_jstr_list ss)`

**Comment by dbuenzli** [comment]
> So, the line `jv_call s "concat" [| jv_of_jstr_list ss |]` should have been writen `jv_call s "concat" (jv_of_jstr_list ss)`

`jv_call s "concat" (Array.of_list ss)` in fact, `jv_of_jstr_list` gives you a JavaScript array.
