### ISSUE TITLE
Base64 decoding

### ISSUE THREAD

**Issue by Armael** [dbuenzli/brr#18]
I just spent some time banging my head against the wall due to the following behavior:

```ocaml
module B64 = Base64
open Brr

let () =
  let encoded = "AAAAAAAAACAAAAAcP9s2eg+QlrxAWRMzMzMzMwAAAAAAAAAAAAAAAA==" in
  let dec_js = Jstr.to_string @@ Result.get_ok @@ Base64.decode (Jstr.of_string encoded) in
  let dec_caml = B64.decode_exn encoded in
  Printf.eprintf "got      : %s\n" (String.escaped dec_js);
  Printf.eprintf "expected : %s\n" (String.escaped dec_caml);
  ()
```
```
got     : \000\000\000\000\000\000\000 \000\000\000\028?\195\1556z\015\194\144\194\150\194\188@Y\01933333\000\000\000\000\000\000\000\000\000\000\000\000
expected: \000\000\000\000\000\000\000 \000\000\000\028?\2196z\015\144\150\188@Y\01933333\000\000\000\000\000\000\000\000\000\000\000\000
```
where `Base64` is the ocaml implementation of Base64 (from the opam library of the same name).
Now, coming back to the documentation of `Brr.Base64.decode`, I can see that it says that the string returned is a binary string, which I assume means it is wrong to call `Jstr.to_string` on it? But then I couldn't find what to do instead.

**Comment by dbuenzli** [comment]
> Now, coming back to the documentation of `Brr.Base64.decode`, I can see that it says that the string returned is a binary string, which I assume means it is wrong to call `Jstr.to_string` on it?

Yes. [`Jstr.to_string`](https://erratique.ch/software/brr/doc/Jstr/index.html#val-to_string) converts your UTF-16 encoded `Jstr.t` to an UTF-8 encoded OCaml string. So those bytes in the `Jstr.t` binary string that are in `[0x80;0xFF]` will be interpreted as unicode chars and be UTF-8 encoded in the result rather than written as bytes which is not what you want. 

I thought maybe going through typed array would [allow you](https://erratique.ch/software/brr/doc/Brr/Tarray/index.html#val-to_string) to get a binary OCaml string. But alas [`Tarray.of_jstr`](https://erratique.ch/software/brr/doc/Brr/Tarray/index.html#val-of_jstr) does the `UTF-8` conversion aswell. 

It seems these JavaScript binary strings are some of  [hack](https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary) used before typed array were introduced. Maybe we should add a few functions to handle these, but I'm not exactly sure where they get used (except as arguments and results of [`atob`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob`) and [`btoa`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa)) and/or if the browser itself does provide facilities for that itself.

**Comment by dbuenzli** [comment]
Looking a bit further on the interwebs I'm tempted to say we should maybe add `Tarray.of_binary_jstr` which does the equivalent of:

```javascript
  var array = new Uint8Array(b64.length);

  for(i = 0; i < b64.length; i++) {
    array[i] = b64.charCodeAt(i);
  }
  return array;
```

**Comment by Armael** [comment]
Thanks for the research. Indeed after a quick google search there doesn't seem to be a built-in function that directly decodes base64 into a typed array. People seem to either do as you mention to copy the binary string into a byte array, or reimplement base64 decoding in pure JS (https://www.npmjs.com/package/base64-arraybuffer).

For my specific use-case, it looks like this would however not be extremely useful, as I need to get my data into an ocaml string or Bytes.t (I'm base64-decoding a big binary blob which represents some serialized content, then deserialize it, where serialization/deserialization is done using the binary codec of the ocaml library [https://gitlab.com/nomadic-labs/data-encoding](data-encoding)). This is basically because data-encoding wants its input data to be in a string or Bytes.t (there's also a streaming API which looks a bit weird and anyway also requires having a Bytes.t as buffer).

So for this use-case it sounds like I should just implement the equivalent of your loop above but copying into a Bytes.t. (Do you know what js_of_ocaml uses to represent Bytes.t?)


Regarding the API of Brr, I guess a `Tarray.of_binary_jstr` function would be useful (possibly documenting the fact that it does allocate a new---more efficiently represented---copy of all the data). Ideally, I think that it would be nice for Base64.decode not to have an output type that can be so easily fed to `Jstr.to_string`, but that would be a breaking change... (e.g. having a Bjstr module?).

**Comment by dbuenzli** [comment]
> For my specific use-case, it looks like this would however not be extremely useful,

Well there is [`Tarray.to_string`](https://erratique.ch/software/brr/doc/Brr/Tarray/index.html#val-to_string). But that of course would involve one more copy. 

> Ideally, I think that it would be nice for Base64.decode not to have an output type that can be so easily fed to `Jstr.to_string`, but that would be a breaking change... (e.g. having a Bjstr module?).

We are at version `0.0.1` if this is really a footgun I don't mind tweaking the API to introduce an abstract say `Base64.data` type to represent base64 encoded data. This would also be future proof if browser get new base64 capabilites. 

A specific `Bjstr` module seems overkill to me it seems the binary string is becoming obsolete API-wise. It is actually unclear to me which browser APIs can/do consume such string…

> (Do you know what js_of_ocaml uses to represent Bytes.t?)

I'm afraid not. But [here](https://github.com/ocsigen/js_of_ocaml/blob/master/runtime/mlBytes.js) lies the answer.

**Comment by dbuenzli** [comment]
I'd like to cut a release soonish (a few weeks). I think it would be good to have a fix for that one. Do you have an opinion on the best course of action ? Should we do something ?

**Comment by Armael** [comment]
Having Base64.data sounds good (and corresponding lookup/conversion functions), if you don't mind the API breakage.

**Comment by dbuenzli** [comment]
Okay thanks I'll do that.

**Comment by dbuenzli** [comment]
@Armael, did something in 3d857a6 could you maybe just have a quick look to tell me if that feels ok.

**Comment by Armael** [comment]
I think that looks good! Thanks for the change :-).

**Comment by dbuenzli** [comment]
Thanks !

**Comment by dbuenzli** [comment]
Now it's my turn to struggle with this. It seems there is still no good way to get an OCaml byte string to a JavaScript binary string.
