### ISSUE TITLE
Missing `window.open`

### ISSUE THREAD

**Issue by dboris** [dbuenzli/brr#19]
I'm not able to find the `window.open` method:
https://developer.mozilla.org/fr/docs/Web/API/Window/open

If it is implemented, would you point me to the right place in the docs? If not, would you like me to submit a pull request for this binding?

**Comment by dbuenzli** [comment]
> I'm not able to find the `window.open` method:

[Can't find](https://erratique.ch/software/brr/doc/Brr/Window/index.html#ops) it either. 

> If not, would you like me to submit a pull request for this binding?

Please do.

**Comment by dboris** [comment]
Any idea why this doesn't work in the ocaml console:
```
# Jv.call Jv.global "open" [| Jv.of_jstr @@ Jstr.v "https://google.com" |];;
- : Jv.t = null
```

The binding I tried to write doesn't work either:
```  
let open' ?(name = Jstr.empty) ?(features = Jstr.empty) w u =
    Jv.to_option Fun.id @@ Jv.call w "open" [|Uri.to_jv u; Jv.of_jstr name; Jv.of_jstr features|]
```

**Comment by dbuenzli** [comment]
Well in my browser (chrome) in the ocaml console it works: that is a popup is blocked… now that I think of it maybe that's the reason why I refrained binding to it: unreliable feature.

**Comment by dbuenzli** [comment]
I don't know what your use case is but I'm tempted to close this as a won't fix. 

It's clearly something browsers want people to refrain from using and for very good reasons in my opinion.

**Comment by dboris** [comment]
You are right, it works. My browser (brave) was blocking the window from opening until I specifically allowed popups on that page. I think opening a new window and loading a url is a fundamental feature (eg. open a dictionary definition of a word in a separate window) and should be part of the api.

**Comment by dbuenzli** [comment]
The problem is that the average user is going to react exactly like you did: doesn't work and will move on. So from a user interaction perspective it's not a good idea to rely on this. 

In general I prefer when APIs lead you to do the right thing. The right thing here being: don't use this. Use links and let people control the windows the way they want it to be (e.g. open in new tab).

**Comment by dboris** [comment]
I agree, it is confusing when it doesn't work as expected. On the positive side, the return value is an option, so you as a programmer will know when it didn't work and can provide alternatives for the user. If you think Brr should discourage features that may lead to confusing UI, you can disregard the PR. On the other hand, programmers that evaluate Brr will be unhappy when basic functionality is missing, so that's a tradeoff.

**Comment by dbuenzli** [comment]
> I agree, it is confusing when it doesn't work as expected.

And that seems to be the default 

> On the positive side, the return value is an option,

Indeed that's interesting, I missed that. By the way are you sure that the returned object can be used as `Window` object like you did in the bindings the docs mention a `WindowProxy` object which I fail to find its docs.

> On the other hand, programmers that evaluate Brr will be unhappy when basic functionality is missing, so that's a tradeoff.

I'm more interested in pleasing end-users than programmers :-)

**Comment by dbuenzli** [comment]
I read a bit further and it should actually work if it comes from a user initiated event, e.g. under a button click, so I'm fine providing this. I can see this being useful in an app to detach a pane from a larger context.

However you have to promise not to do that:

> (eg. open a dictionary definition of a word in a separate window)

**Comment by dboris** [comment]
Thanks for adding the binding.
