### ISSUE TITLE
clip

### ISSUE THREAD

**Issue by nickbetteridge** [dbuenzli/brr#22]
Is there any chance the clip signature could be updated

from ```val clip : ?fill_rule:Fill_rule.t -> t -> Path.t -> unit```

to ```val clip : ?fill_rule:Fill_rule.t -> ?path:Path.t ->  t -> unit```

in order to comply with ```https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clip```?

-> I have a scenario where I don't know, but wish to retain, the previous clipping region

**Comment by dbuenzli** [comment]
I would rather say no. This looks like opening a can of worms: why not update `stroke` for the same signature etc. ?  

IIRC the Brr API doesn't expose the implicit/immediate canvas API (`beginStroke` etc.) which is harder to use in a compositional manner (implicit state). 

Seems easy enough to keep a binding on your side if you really need it no ?

**Comment by nickbetteridge** [comment]
Thanks for getting back so quickly.

I'll do the binding on my side, as you suggest.

Thanks again.
