### ISSUE TITLE
Question: Unbound module issues for `todomvc.ml` in ocaml-lsp (merlin)

### ISSUE THREAD

**Issue by sidkshatriya** [dbuenzli/brr#26]
I'm trying to get ocaml-lsp to work on `todomvc.ml` however ocaml-lsp (merlin I guess) is complaining about unbound modules `Brr` etc. I guess I have to compile some stuff for ocaml-lsp to start picking things up. 

I tried `ocamlbuild -use-ocamlfind test/todomvc.byte` -- this command works but that does not help with merlin issues. 

The `.merlin` has `test/**` but it does not get picked up by ocaml-lsp.

**Comment by dbuenzli** [comment]
I don't know. I suppose you are trying from the repo ? Maybe simply install `brr`,  copy the test/todomvc.* in a fresh directory and try with `dune`, follow the instructions [here](https://erratique.ch/software/brr/doc/web_page_howto.html#dune_quick).

**Comment by sidkshatriya** [comment]
This was a good suggestion -- thank you! By trying in a fresh dune project I was able to get ocaml-lsp (merlin) showing no problems.

**Comment by dbuenzli** [comment]
Excellent. Have fun !
