### ISSUE TITLE
Missing external function when compiling brr

### ISSUE THREAD

**Issue by joprice** [dbuenzli/brr#27]
I get the error `The external function 'caml_js_meth_call' is not available` when trying to compile a library using brr.

**Comment by joprice** [comment]
It looks like this was due to a missing dependency on js_of_ocaml. I assumed this would be brought in transitively.

**Comment by dbuenzli** [comment]
You shouldn't have to depend on `js_of_ocaml`. Could you just please confirm you were not maybe simply missing the `-no-check-prims` flag ? See the build instructions [here](https://erratique.ch/software/brr/doc/web_page_howto.html#dune_quick).

**Comment by joprice** [comment]
Yes thank you! That was it. I copied my dune file from a previous experiment with brr and removed some things I thought were just from my troubleshooting.

**Comment by dbuenzli** [comment]
Ok thanks for the confirmation I hope we can one day get rid of that e.g. by solving #2.
