### ISSUE TITLE
note and mutable data structures

### ISSUE THREAD

**Issue by joprice** [dbuenzli/brr#29]
I'm interested in measuring the performance of the todomvc example versus implementations in other languages. My first thought when looking over the code was whether the use of immutable data structures (ocaml's list) would become an issue, especially when removing an element at an arbitrary index. I saw this before when running the todomvc benchmark against a version written using bucklescript-tea. Is it possible for Note to work with mutable data, or maybe the approach would be to use a persistent data structure with better asymptotics?

**Comment by dbuenzli** [comment]
Why not ?

**Comment by dbuenzli** [comment]
> My first thought when looking over the code was whether the use of immutable data structures (ocaml's list) would become an issue

But as usual, don't make assumptions, measure and find the bottlenecks.

**Comment by joprice** [comment]
For the mutability question, I thought that there might be a reliance on reference equality that makes using a mutable array trickier. On the assumptions, as I said I hit this before, but of course the idea would be to compare it against other frameworks, and against itself with mutable data.

**Comment by dbuenzli** [comment]
I don't have these things in my head but I don't think there's any problem on returning the same imperative `Todos.t` value [here](https://github.com/dbuenzli/brr/blob/466c9bb7611460933fc6001c868b692711dd3d34/test/todomvc.ml#L112-L118).
