### ISSUE TITLE
Can't install brr in windows

### ISSUE THREAD

**Issue by davesnx** [dbuenzli/brr#34]
Hey @dbuenzli 

I started using brr and it's great, thanks for the effort. It's not a blocker for my project, but I still wanted to report it just in case there's something broken for Windows users.

I'm using esy but I believe have not much to do here, but when building brr in Windows breaks with the following: https://github.com/davesnx/query-json/runs/5175859022?check_suite_focus=true#step:10:32

Brr version: 0.0.2 
esy: 0.6.10

**Comment by dbuenzli** [comment]
I don't know. I'm not familiar with esy. 

But I don't think there should be a particular particular problem on windows. `brr` has no system dependencies.

You may want to check with the people in charge of esy's package repository.

**Comment by dbuenzli** [comment]
I had a closer look, roughly I suspect that `esy` is unable to create the [`_build`](ihttps://github.com/davesnx/query-json/runs/5175859022?check_suite_focus=true#step:10:42). This seems to lead to the ocamlbuild plugin being created in the source tree, which leads to `ocamlbuild` hygiene violation.

I don't think the error is on this side. Feel free to reopen with further details if you think it is.

**Comment by Et7f3** [comment]
brr is pulled directly from spam repository: https://github.com/davesnx/query-json/blob/753f4f3c0386907e453cdba6ce6f38e79be668f7/esy.lock/index.json#L1318-L1348

esy expose `DUNE_BUILD_DIR` for dune to get a writable folder.
Where is this folder created so the call can be adapted.

**Comment by dbuenzli** [comment]
This folder is created by ocamlbuild.

**Comment by ManasJayanth** [comment]
This issue is only seen in ocamlbuild `0.14.1` and not on `0.14.0`

**Comment by dbuenzli** [comment]
Not sure exactly what changed, tut this, in the new release, seems to deal with folders https://github.com/ocaml/ocamlbuild/pull/302 you may want to check that. 

These CI systems, without access to the build dir, make it hard to see what happens and what the problem is exactly. I think you should try to reproduce that on a machine and look around.

**Comment by dbuenzli** [comment]
Keep an eye on this discussion https://github.com/ocaml/ocamlbuild/issues/316
