### ISSUE TITLE
Illegal invocation using alert function

### ISSUE THREAD

**Issue by mooreryan** [dbuenzli/brr#35]
Hey, so I get a kind of weird error.  When calling this function

```ocaml
let alert msg =
  match Jv.find Jv.global "alert" with
  | None -> prerr_endline "no alert"
  | Some alert -> ignore @@ Jv.apply alert Jv.[| of_string msg |]
```

I get an illegal invocation error.  

However, this one is fine...almost the same, except for a print function stuck in there.  (No idea why the print function helps...)

```ocaml
let alert msg =
  match Jv.find Jv.global "alert" with
  | None -> prerr_endline "no alert"
  | Some alert ->
      (* Needs this print to work. *)
      prerr_endline "yay!";
      ignore @@ Jv.apply alert Jv.[| of_string msg |]
```

This also works fine.

```ocaml
let alert msg =
  match Jv.find Jv.global "window" with
  | None -> prerr_endline "no window"
  | Some window -> ignore @@ Jv.call window "alert" Jv.[| of_string msg |]
```

All of them work fine in dev mode, but when in release mode, the error happens.  

I'm using js_of_ocaml 4.0.0 and brr 0.0.3.

Have you run in to this sort of thing, or am I just doing something wrong?

**Comment by dbuenzli** [comment]
It's unclear in your message whether the last one works both in release or dev mode. But in any case that's the correct one and it should.

[`alert`](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-alert-dev) is not a function it's a method of the window object. Invoking it as a function means `this` won't refer to the right value and result in the illegal invocation you witness.

**Comment by mooreryan** [comment]
That's correct, the last one works in both cases.  Thanks for the explanation regarding `alert` and `this`, it makes sense.

As a follow up question, is there a reason that invoking `alert` like how the FFI cookbook (using `apply` rather than `call` on `window`) has it works (in both modes)? 

```ocaml
let alert v =
  let alert = Jv.get Jv.global "alert" in
  ignore @@ Jv.apply alert Jv.[| of_string v |]
```

It's interesting that that works, but the `Jv.find` and handling the option way in the previous post does not work.

**Comment by dbuenzli** [comment]
I have absolutely no idea, tell me if you find out :–)  These things are better discussed on discuss.ocaml.org where there are more people who may answer your questions. So I'm going to close this.
