### ISSUE TITLE
error on console evaluation

### ISSUE THREAD

**Issue by joprice** [dbuenzli/brr#4]
I'm getting this error when I hit enter to submit a line for evaluation in the console:

```
ocaml_console.js:1788 Uncaught TypeError: s.toUtf16 is not a function
    at caml_jsstring_of_string (ocaml_console.js:1788)
    at caml_js_object (ocaml_console.js:2473)
    at set$1 (ocaml_console.js:3826)
    at caml_call2 (ocaml_console.js:2791)
    at HTMLTextAreaElement.<anonymous> (ocaml_console.js:4151)
```

I do see the definition of `MlBytes.prototype.toUtf16` in `ocaml_console.js`.

**Comment by dbuenzli** [comment]
Does that happen on any evaluation ? 

I can't reproduce that on macos with firefox or chrome and js_of_ocaml 3.6.0. 

What's your browser/os/js_of_ocaml versions ?

**Comment by dbuenzli** [comment]
I can reproduce with 3.7.0. Must be related to the change in string representation.

**Comment by dbuenzli** [comment]
The recursive module used by `note` also seems to explode with 3.7.0. I suggest you try with 3.6.0 for now.

**Comment by dbuenzli** [comment]
This is due to some assumptions that `brr`'s FFI does that no longer holds I want to see what the results of the discussion [here](https://github.com/ocsigen/js_of_ocaml/pull/997#issuecomment-694925765) before moving on to fix it.

So for now if you want to play with `brr` definitively stick to 3.6.0

**Comment by joprice** [comment]
With 3.6.0, I get a build error:

```
Undefined symbols for architecture x86_64:
  "_caml_list_of_js_array", referenced from:
      _caml_builtin_cprim in camlprim8593b7-7526a1.o
  "_caml_list_to_js_array", referenced from:
      _caml_builtin_cprim in camlprim8593b7-7526a1.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by dbuenzli** [comment]
I can't help you if you don't provide details. Where does this build error happen ?

**Comment by joprice** [comment]
No problem. This is from a private repo right now so I'll reproduce it in a smaller context, push it to a repo and do a bit more debugging on my own first.

**Comment by dbuenzli** [comment]
I don't necessarily need to have a public repo. I need to understand the context where it happens. 

If that is in your own code and not in the brr libraries or the console extension compilation, then you should add `-no-check-prims` during the bytecode linking phase.

**Comment by joprice** [comment]
Here's the full compilation command that includes versions (ocaml 4.10.0, jsoo 3.6.0, brr a7c39a0). It does include -no-check-prims

```
ocamlc brr-test/main.exe (exit 2)
(cd _build/default && /nix/store/5c6fhzd56dg45l1sf8yfhaqh1sy0n482-ocaml-4.10.0/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -w @A-42-44-48-45-4 -unboxed-types -short-paths -g -o brr-test/main.exe -custom /nix/store/37sj85491pv48vrgqnn9dx75xfklj8j3-brr/lib/ocaml/4.10.0/site-lib/brr/brr.cma /nix/store/i67b8l4api4fqjflnvl599kwlb7r92ks-js_of_ocaml-3.6.0/lib/ocaml/4.10.0/site-lib/js_of_ocaml/js_of_ocaml.cma -I /nix/store/i67b8l4api4fqjflnvl599kwlb7r92ks-js_of_ocaml-3.6.0/lib/ocaml/4.10.0/site-lib/js_of_ocaml /nix/store/5c6fhzd56dg45l1sf8yfhaqh1sy0n482-ocaml-4.10.0/lib/ocaml/compiler-libs/ocamlcommon.cma /nix/store/5c6fhzd56dg45l1sf8yfhaqh1sy0n482-ocaml-4.10.0/lib/ocaml/compiler-libs/ocamlbytecomp.cma /nix/store/635wn4j2w2ngamhp0c5isi3f9k4vjg5c-easy-format-1.3.2/lib/ocaml/4.10.0/site-lib/easy-format/easy_format.cma /nix/store/8b5z7af9wsb5bf314xk7jmvpprn4ih33-biniou-1.2.1/lib/ocaml/4.10.0/site-lib/biniou/biniou.cma /nix/store/9bd76jpk6wcmvq03gh6ji9wv30wh9iap-yojson-1.7.0/lib/ocaml/4.10.0/site-lib/yojson/yojson.cma /nix/store/pm734n7pfyaski26vg5lkm90l4l65k8l-js_of_ocaml-compiler-3.6.0/lib/ocaml/4.10.0/site-lib/js_of_ocaml-compiler/js_of_ocaml_compiler.cma /nix/store/5c6fhzd56dg45l1sf8yfhaqh1sy0n482-ocaml-4.10.0/lib/ocaml/compiler-libs/ocamltoplevel.cma /nix/store/08avi0w78k3li2rm9cw3q60im51cbzng-js_of_ocaml-toplevel-3.6.0/lib/ocaml/4.10.0/site-lib/js_of_ocaml-toplevel/js_of_ocaml_toplevel.cma /nix/store/37sj85491pv48vrgqnn9dx75xfklj8j3-brr/lib/ocaml/4.10.0/site-lib/brr/poke/brr_poke.cma brr-test/.main.eobjs/byte/dune__exe__Main.cmo -rectypes -linkall -no-check-prims)
Undefined symbols for architecture x86_64:
  "_caml_list_of_js_array", referenced from:
      _caml_builtin_cprim in camlprim80c5c7-a95c07.o
  "_caml_list_to_js_array", referenced from:
      _caml_builtin_cprim in camlprim80c5c7-a95c07.o
ld: symbol(s) not found for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm guessing this isn't something specific with brr, but with my jsoo version and compilation flags, so feel free to close.

**Comment by dbuenzli** [comment]
No it's just that js_of_ocaml libraries provide a C dummy stub for their primitives so that the link to bytecode does not fail. 

These C dummy primitives are just raising versions of the functions. This means that if you try to invoke a bytecode executable produced to be processed by `js_of_ocaml` you get an exception in the face that the primitive is not implemented.

It turns out I'm a very lazy person and can't be bothered to write dumb stuff if I can avoid it; something you can by just compiling your bytecode with `-no-check-prims`. The effect is exactly the same if you try to run the bytecode executable is will complain about a missing primitive.

**Comment by dbuenzli** [comment]
Regarding your error specifically I suspect you need to remove the `-custom`.

**Comment by dbuenzli** [comment]
Ah and I see now you are linking the `js_of_ocaml` lib in that invocation so that error should not happen but it's likely due to https://github.com/ocsigen/js_of_ocaml/issues/1028. 

But in any case you should not use `-custom` for producing bytecode to be jsoo'ed it doesn't make sense.

**Comment by joprice** [comment]
That's not a flag I'm adding in dune, so I'll have to figure out where it's coming from.

**Comment by dbuenzli** [comment]
I guess it's the default build instructions for bytecode executables (that makes them relocatable but it doesn't make sense for jsoo). I'm not using `dune` so I can't help you but likely can tweak the default link flags see [here](https://dune.readthedocs.io/en/stable/concepts.html#ocaml-flags).

**Comment by dbuenzli** [comment]
This should not work with `js_of_ocaml.3.7.1`. 

Regarding your dune problem I added a comment on the web page howto, see a3322ee53134e779b877e9b0876e86d956b578af

**Comment by dbuenzli** [comment]
> This should not work with `js_of_ocaml.3.7.1`.

This should NOW work !

**Comment by dbuenzli** [comment]
@joprice  commit 12bbd8bc13f52faf945843a6e6593c34d now give full instructions for how to poke your program with `dune`.

**Comment by joprice** [comment]
Nice! I did try it out when you pushed the last commit and didn't get it working, but I have a convoluted setup by now. I'll create a clean project and follow it and make sure I can't repro the same issue.

**Comment by dbuenzli** [comment]
Further tweaks were needed to make the program modules available in the console, see 41580885f40bfd184c3d8. Also you should now be able to clear your `opam pin`.

**Comment by joprice** [comment]
The recent changes work perfectly for me!

**Comment by dbuenzli** [comment]
Excellent, glad to know.
