### ISSUE TITLE
In default dune builds, the brr library raises an exception in web workers

### ISSUE THREAD

**Issue by andrewray** [dbuenzli/brr#40]
I think without aggressive dead code elimination (which is the case with --profile=dev dune builds) there is something that accesses the global document object, and this causes an exception when the code is run in a web worker context.

With --profile=release things seem to be OK.

Maybe worth some comment in the documentation, though it would be really nice if things worked smoothly in dev mode also.

**Comment by dbuenzli** [comment]
Yes ! It was fixed in https://github.com/dbuenzli/brr/commit/655a3d6686d7e551fead2f1aa80e25b416a35752. I will make a release anytime soon.

**Comment by dbuenzli** [comment]
(if you can confirm that `opam pin brr --dev` works for you, it's even better)

**Comment by andrewray** [comment]
Yup, it works by pinning the dev version.  Thanks!

**Comment by dbuenzli** [comment]
Excellent, thanks for the confirmation. 

> Maybe worth some comment in the documentation, though it would be really nice if things worked smoothly in dev mode also.

It's not only about `dev` mode. I like to be able to have a single js artefact and simply: 

```ocaml
let () = if Brr_webworkers.Worker.ami () then worker () else main ()
``` 

(if you write the the artefact in the html file and perform [terrible circonvolutions](https://gist.github.com/dbuenzli/0cbad35b9d0a828b17d15aa026e230f2#file-work_queue-ml-L32-L44) it's even possible to make it work over the `file://` protocol).
