### ISSUE TITLE
Support for touch events

### ISSUE THREAD

**Issue by zapashcanon** [dbuenzli/brr#46]
Hi,

I've been looking for predefined [touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) in [Brr.Ev](https://erratique.ch/software/brr/doc/Brr/Ev/index.html#predefined_types) but couldn't find anything in the whole repository apart some [constant values](https://erratique.ch/repos/brr/tree/src/note/brr_note_kit.mli#n472).

Do you plan to add them ? If not, would you accept a PR ?

**Comment by dbuenzli** [comment]
Rather not. Touch events are not supported on non-mobile Safari and I suspect they may never be. From the page you linked to:

> To support both touch and mouse across all types of devices, use [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) instead.

which are already [supported](https://erratique.ch/software/brr/doc/Brr/Ev/Pointer/index.html).

**Comment by zapashcanon** [comment]
I used pointer events instead but forgot to reply. Thanks !
