### ISSUE TITLE
Parentheses are not percent encoded

### ISSUE THREAD

**Issue by novemberkilo** [dbuenzli/brr#47]
I'd like to report what I think is a bug in the URL (percent) encoding of `Uri.with_uri`

Consider the following minimal example:

```
open Brr
let () =
  let location = Window.location G.window in
  let msg =
    Jstr.to_string
    @@ Uri.to_jstr
    @@ Result.get_ok
    @@ Uri.with_uri ~path:(Jstr.v "/some/path/that/includes/?(parens)") location in
  El.set_children (Document.body G.document) El.[txt' msg]
```

The output of this is: 

```
file:///some/path/that/includes/%3F(parens)
``` 

when I think it should be

```
file:///some/path/that/includes/%3F%28parens%29
```

**Comment by dbuenzli** [comment]
Between the various RFCs and the browser's own notion of URL, the whole URL space is in a very sad state I'm afraid.

In any case parentheses where unreserved in RFC2396 but became in RFC3986 (even though they are not delimiters per se). The module just uses the browser's [`encodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#description) function which does not escape those.

I'll make a note in the docs but I do not plan to change that.
