### ISSUE TITLE
The parseInt FFI example is slightly confusing

### ISSUE THREAD

**Issue by benjamin-thomas** [dbuenzli/brr#48]
Hello!

I found the FFI example documented here slightly confusing: https://erratique.ch/software/brr/doc/ffi_cookbook.html#fun

To my knowledge, `parseInt` won't ever throw, but rather return `NaN`:

```
$ node
Welcome to Node.js v16.20.0.
Type ".help" for more information.
> parseInt("wat")
NaN
```

See what I've done below:

### BEFORE

```ocaml
(* NOTE: matching on the exception variant will never actually occur in this example. Or will it?? *)
let parse_int' = Jv.get Jv.global "parseInt"
let parse_int ?radix s =
  let r = Jv.of_option ~none:Jv.undefined Jv.of_int radix in
  match Jv.apply parse_int' Jv.[| of_jstr s; r |] with
  | exception Jv.Error e -> Error e
  | v -> Ok (Jv.to_int v)
```

### AFTER

```ocaml
let parse_int' ?radix s : (int, Jv.Error.t) result =
  let r = Jv.of_option ~none:Jv.undefined Jv.of_int radix in
  match Jv.apply (Jv.get Jv.global "parseInt") Jv.[| of_jstr s; r |] with
  | v -> (
      let v' = Jv.to_float v in
      match Float.is_nan v' with
      | true -> Error (Jv.Error.v (Jstr.v "Reject NaN!"))
      | false -> Ok (int_of_float v'))
;;
```

Maybe it'd be worth it to emphasize that we can deal with 2 types of functions in JS: ones that fail, and ones that silently do the wrong thing and handle them accordingly?

Here's an example of a builtin function that trows:

```
> decodeURI('%')
Uncaught URIError: URI malformed
    at decodeURI (<anonymous>)
```

What do you think?

**Comment by dbuenzli** [comment]
> What do you think?

I'll simply add a comment that in practice `parseInt` doesn't raise and that this is for demonstration purposes only. 

`decodeURI` has no optional argument, something you hit quite a bit when you bind to JavaScript.
