### ISSUE TITLE
Namespace and the svg story.

### ISSUE THREAD

**Issue by pveber** [dbuenzli/brr#54]
@schutm provided a nice [module](https://gitlab.com/schutm/brr_svg) to generate SVG contents. The only drawback is that one has to use `Obj.magic` to get said content inserted into a HTML page. This is because there is currently no way to create values of type `El.t` with a namespace specification, as required to create SVG elements. 

After seeing #17 and the arguments for not including it, how about adding a `El.v_ns` function? That way, it would be possible to have a `brr_svg` or a `brr_mathml` library that do not force `Obj.magic` on their users, with no risk of performance regression.

**Comment by dbuenzli** [comment]
That can be done. 

Note though that in general bindings are full of (implicit) `Obj.magic`.

**Comment by pveber** [comment]
Ah right, you're saying that I'll feel better if I give it another name and restrict its type to `Brr_svg.El.t -> Brr.El.t`? After second thought, it's true that keeping a different type for SVG elements/attribute is not a bad thing either. Ok then, maybe it's not worth the trouble. Thanks!

**Comment by dbuenzli** [comment]
No I'm happy to add the function suggest, but if you think it's not worthwhile I'm happy too :-)
