### ISSUE TITLE
javascript record

### ISSUE THREAD

**Issue by nickbetteridge** [dbuenzli/brr#56]
Greetings, I'm in the process of writing a binding and the webidl has defined a record : `typedef record<DOMString, boolean> MyName`  - giving, in plain javascript : `#{ "a": true, "b": false }` etc - is there any simple way of providing the construct with Jv?

**Comment by dbuenzli** [comment]
As far as I can tell this is not part of the JavaScript standard yet and still [a proposal](https://github.com/tc39/proposal-record-tuple). None of the browser consoles of `firefox` and `chrome` or `safari` accept that syntax.

Reading the [definition](https://webidl.spec.whatwg.org/#idl-record) of record in webidl suggest me you should likely simply treat as a "platform objects", that use [these functions](https://erratique.ch/software/brr/doc/Jv/index.html#objects) of the FFI.
